#cloud-config
timezone: ${TIMEZONE}

disable_root: true
ssh_pwauth:   false

users:
  - name: admin
    ssh-authorized-keys:
      - ${ADMIN_SSH_KEY}
    groups: sudo
    shell: /bin/bash
  - name: manager
    ssh-authorized-keys:
      - ${MANAGER_SSH_KEY}
    groups: sudo
    shell: /bin/bash
    
runcmd:
 - export _PRIVATE_IP=$(curl -s http://169.254.169.254/metadata/v1/interfaces/private/0/ipv4/address)
 - sed -i "s/listen 80/listen $${_PRIVATE_IP}:80 proxy_protocol/" /etc/nginx/sites-available/magento2.conf
 - systemctl restart nginx
