#cloud-config
package_update:  true
package_upgrade: true
packages:
 - wget 
 - postfix
 - dnsutils
 - unzip
 - iptables
 - git
 - patch
 - python3-pip
 - acl
 - attr
 - snmp
 - rsync

disable_root: true
ssh_pwauth:   false

users:
  - name: admin
    ssh-authorized-keys:
      - ${ADMIN_SSH_KEY}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
  - name: manager
    ssh-authorized-keys:
      - ${MANAGER_SSH_KEY}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    
write_files:
- path: /opt/manager/droplet/create_droplet.sh
  owner: 'manager:manager'
  permissions: '0640'
  defer: true
  content: |
    ${create_droplet}
- path: /opt/manager/droplet/delete_droplet.sh
  owner: 'manager:manager'
  permissions: '0640'
  defer: true
  content: |
    ${delete_droplet}

runcmd:
 - export _PRIVATE_IP=$(curl -s http://169.254.169.254/metadata/v1/interfaces/private/0/ipv4/address)
 - cd /usr/local/bin
 - DOCTL_VERSION=$(curl -s https://api.github.com/repos/digitalocean/doctl/tags 2>&1 | head -3 | grep -oP '(?<="v)\d.*(?=")')
 - wget https://github.com/digitalocean/doctl/releases/download/v$${DOCTL_VERSION}/doctl-$${DOCTL_VERSION}-linux-amd64.tar.gz
 - tar xf doctl-$${DOCTL_VERSION}-linux-amd64.tar.gz
 - rm doctl-$${DOCTL_VERSION}-linux-amd64.tar.gz
 - chmod 700 doctl
 - chmod 711 /home/admin
  
