write_files:
- path: /etc/ssh/ssh_config
  content: |
    Host github.com
     Port 22
    Host ${SSH_CONFIG_HOST}
     Port ${SSH_PORT}
     StrictHostKeyChecking no
     UserKnownHostsFile=/dev/null
     ConnectTimeout=30
     LogLevel ERROR
  append: true

runcmd:
 - export _PRIVATE_IP=$(curl -s http://169.254.169.254/metadata/v1/interfaces/private/0/ipv4/address)
 - sed -i -e '/^Port/s/^.*$/Port ${SSH_PORT}/' /etc/ssh/sshd_config
 - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
 - sed -i -e "/^AddressFamily/s/^.*$/AddressFamily inet/" /etc/ssh/sshd_config
 - sed -i -e "/^ListenAddress/s/^.*$/ListenAddress $${_PRIVATE_IP}/" /etc/ssh/sshd_config
 - systemctl restart sshd
